[site]
title = "Sheng Wang"
description = "Personal website of Sheng Wang, focusing on agent systems, LLM super-alignment, and data synthesis."
favicon = "/favicon.png"
last_updated = "April 8, 2026"

[author]
name = "Sheng Wang"
title = "PhD Graduate in Computer Science"
institution = "The University of Hong Kong"
avatar = "/bio.jpeg"

[social]
email = "forence1999@outlook.com"
google_scholar = "https://scholar.google.com/citations?user=BYxiWaIAAAAJ&hl=en"
github = "https://github.com/Forence1999"
linkedin = "https://www.linkedin.com/in/forence1999"
x = "https://x.com/Forence1999"
cv = "/resume.pdf"
wechat_qr = "/wechat.jpg"
wechat_id = "Forence1999"

[features]
# Show a like button on the about page
enable_likes = false

# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = false
locales = ["en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = false
# Show a language switcher on the top right corner
switcher = false

[i18n.labels]
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Experience"
type = "page"
target = "experience"
href = "/experience"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"
