type = "card"
title = "项目经历"
description = "研究、产品与创业相关经历。"

[[items]]
title = "AI家庭教育"
subtitle = "领导者"
date = "2025.02 - 2026.01"
content = '''
- 广泛阅读书籍（涵盖心理学、家庭教育、团队管理、项目管理、产品设计、人物传记、内容运营、用户运营等），建立了全面的商业视角。
- 组建了涵盖全栈开发、算法研究、产品设计、用户运营和内容运营的跨职能团队，进一步磨练了领导力。
- 迭代优化多方面的AI原生SOP，覆盖市场调研、用户建模、产品迭代、开发协作、内容生产、用户访谈和社区运营，借助前沿AI产品数倍提升团队协作和项目管理效率。
- 持续迭代用户画像、旅程、痛点、需求和解决方案，成功确定了产品的市场定位与MVP，提升了快速迭代优化的能力。
- 全面提升了全栈开发能力，加深了对未来编程范式（即 vibe coding）的理解与熟练应用。
'''

[[items]]
title = "智能音箱"
subtitle = "核心贡献者"
date = "2022.09 - 2024.09"
content = '''
- 针对多用户个性化的高资源消耗问题，我们提出了 MoS、PRoLoRA 等解决方案，成倍减少了常规 LoRA 所需要的资源消耗。
- 针对多模态的不良表现，我们提出了 ProReason 方案解耦多模态任务的视觉和推理能力，并利用 LLM 辅助推理，提升了多模态性能。
- 针对端侧等低资源场景下的模型部署，我们提出了 QSpec 技术共享量化权重与 KV Cache，借助 speculative decoding 框架实现了模型无损推理加速。
- 构建粤语常识、事实生成、复杂推理等任务的评估数据集，并对比了 35 个开源/闭源 LLM 在粤语上的性能差异。
- 从 1939 小时口齿不清视频中提取音频，利用离线语音识别（ASR）服务转换为文本，并通过人工校对完成数据集构建。
- 实现 MoChA 与 Whisper 模型用于端到端 ASR，为口齿不清语音设计改进模块，词表扩增、post-training 等方案提升粤语 ASR 性能。
- 基于“aidatatang_200zh”语料库训练基于 Transformer 的声学模型和 HiFi-GAN 声码器用于语音合成（TTS），在此基础上使用说话人编码器注入定制化声音。
'''

[[items]]
title = "智能助行机器人 - 语音算法"
subtitle = "唯一贡献者"
date = "2021.09 - 2022.12"
content = '''
- 在香港大学周亦卿楼 4 层，共计放置 14 个声源位置，最终采集到 1984 条多通道麦克风数据，共计约 500 分钟。自学语音信号分帧、加窗、滤波、归一化等预处理技术，并预处理原始数据。
- 调研并测试传统和基于学习的语音降噪和语音分离算法，最终选用 NSNet2 模型对语音信号进行降噪处理。
- 自学声音事件定位和检测相关的特征与算法，提取 GCC-PHAT 和 MFCC 特征，并使用集成学习的思想设计了一个并行模块。将 RD3Net 的声源定位准确率从 88.2% 提升至 93.6%。在真实场景中，结合降噪模块，效果理想，实现了基本的室内语音导航。
- 使用 A2C 和 D3QN 强化学习算法对模型在实际场景中在线微调，并在仿真与真实环境中获得预期效果。
- 基于 TDOA 设计低计算负载的传统声源定位算法，实现近场高精度连续识别以监测用户跌倒求救。
'''

[[items]]
title = "全美大学生数学建模竞赛 · 一等奖"
subtitle = "队长"
date = "2020.03 - 2020.04"
content = '''
- 学习多种数据挖掘和建模技术，对如何处理并利用数据有了进一步的理解。
- 分析亚马逊商品的评分与评论数据，识别关键模式、关系和指标等，并挖掘潜在功能设计及为公司制定电商销售策略，以提高产品信誉和销量。
- 组织团队合理规划时间与任务安排，搜集文献并设计总体建模方案，撰写和检查最终论文。
'''

[[items]]
title = "新加坡国立大学暑期人工智能夏令营"
subtitle = "主要贡献者之一"
date = "2019.07 - 2019.07"
content = '''
- 合作完成“基于人脸识别和骨架检测的罪犯抓捕系统”。
- 设计特征提取模块，调试并优化 AlphaPose 算法，整合团队成员所有模块以完成整个项目。
- 课程系统评分排名第一，获得评委老师们的认可，荣获本项目“最佳小组”与“最佳个人”双重奖项。
- 体验全英文授课环境，提高了英语听说读写能力，完成了高强度的学习与项目任务，提升了快速学习、抗压和团队协作能力。
'''
